let Avengers;
number=12;
let Jules;
nom="César";
let Etoiles;
number="Une infinité";
let Message;
Message="Que le force soit avec vous";
let FaceID;
FaceID=true;
let Ordinateur;
number=3000;
let Nains;
Nom="Prof, Timide, Joyeux, Simplet, Atchoum, Dormeur, Grincheux";
let Tinder;
Nom="Pico Senpai";
let Naruto;
number="beaucoup";
let Défauts;
number="Perfectionniste, obstiné, ambitieux";
let Anne;
number="Oui?";
let Panier;
number="Un bon gros PC";
let Guerre;
number=116;
let Bière;
number="Quand t'en bois beaucoup t'es bourré";
let Président;
number="Macron pour 1000 ans";